### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by devil-works** [devil-works/devil-code#2]
- [x] Hide the table of content (sm ~ md)  https://devil-code.com/blogs
- [x] Blog url https://devil-code.com/blogs/view/Mac4 → https://devil-code.com/blogs/${slulg}/${title}
- [x] Header - position fixed
- [x] Blogs- Hero image
- [x] Create a page about policy 
- [x] Create a page to edit an article
- [x] Add archive links

**Comment by devil-works** [comment]
devil-code\html\templates\layout\default.php
